# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NmY1N2Q3NDcwMWFhMWJlODE0ZTc1N2FkMGNhOWQ1MGJjZDQ2ZDE1ODMyY2U4ZDkwMTZlOTFlMDU5OGU4ZDYwNDcyNDkxYjA0OGMxN2I3ZTFkMjkwMmNjNWQzZDQ2NTYzMWRhZTY5ZmM4NGJlMGViYzI2MDI3ZjAwYTMzNzNkYjQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
